server:
  port: 8889
spring:
  application:
    name: micro-admin-registry-server
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000


    


